### PR TITLE
Map GB/C RAM banks in RAVBA-M

### LINKED ISSUE #36: GB platform memory mapping
GB memory mapping needs to be reviewed based on [this issue](https://github.com/libretro/gambatte-libretro/issues/122). It looks like main memory on supported clients is located past 0xC000, so it is possible that the reference map used by RA is wrong, and the one now used by Gambatte is actually correct.

### PR DESCRIPTION
**Pull request by rzumer**
Closes #36.

This adds RAM banks to the end of the memory map (offset 0x10000).

For GB, it is a mirror of the 0xD000\~0xDFFF area. For GBC, it is the seven memory banks mapped directly. In most cases, that means 0x10000\~0x10FFF is a mirror of 0xD000\~0xDFFF. On the GB end the bank is remapped for compatibility in case someone decides to use the first static memory bank instead of the banked memory area.

I have corresponding PRs ready to go for the compatible libretro cores when this is merged.

### CODE REVIEW

File: RAVBA-M/src/win32/MainWnd.cpp [hunk 1]
```diff
@@ -571,6 +580,7 @@ bool MainWnd::FileRun()
 		RA_SetConsoleID( 4 );
 		RA_ClearMemoryBanks();
 		RA_InstallMemoryBank( 0, ByteReader, ByteWriter, 0x10000 );
+		RA_InstallMemoryBank( 1, BankedRAMReader, BankedRAMWriter, 0x1000 );
```
Comment (Jamiras) [inline RAVBA-M/src/win32/MainWnd.cpp]: Banking is specifically a GBC feature, I see no reason to duplicate bank 1 for GB - it would effectively be mirror/echo RAM, which we encourage devs not to use.

Also note that `gbWram` is NULL in GB mode (https://github.com/RetroAchievements/RAEmus/blob/master/RAVBA-M/src/gb/GB.cpp#L2184-L2202), so your changes would cause the emulator to crash if attempting to view this bank.

Comment (rzumer) [reply RAVBA-M/src/win32/MainWnd.cpp]: My concern with not mirroring the bank for GB is that for a title that runs in both GB and GBC mode and uses bank-switching in GBC mode, the contents of the bank-switched RAM (0xD000\~0xDFFF) will not necessarily match on both systems, even if bank 1 contents are the same. That said I'm not sure if there *is* a title that is compatible with both models and uses bank-switching on GBC.

Comment (rzumer) [reply RAVBA-M/src/win32/MainWnd.cpp]: As mentioned in chat, it seems unlikely for a GB-compatible title to be making use of bank-switching on GBC, though I could not find a definitive answer. For now I have removed the duplicate RAM mapping for GB. If it ends up being needed for cross-platform compatibility, it can be implemented later.

**Comment by rzumer** [comment]
Updated based on https://github.com/RetroAchievements/RAIntegration/issues/364.
